#!/bin/bash
filesystem=$filesystem
echo Which filesystem?
read filesystem


BREAK="============================================================"
echo -ne "\n $BREAK \n \t Disk Usage for filesystem $(date +'%F') \n $BREAK \n\n";
df -hP $filesystem;
echo -e "\n $BREAK"


BREAK="============================================================"
echo -e '\n Volume Group Usage';
vgs $(df -h $filesystem | grep dev | awk '{print $1}'| cut -d\- -f1| cut -d\/ -f4);
echo -e "\n $BREAK"


BREAK="============================================================"
echo -e Largest Folders:$filesystem;
du -xSk $filesystem | sort -rn | head -20|awk '{printf "%d MB\t%s\n",($1/1024),$NF}' && echo -e "\n\n";
echo -e "\n $BREAK"

BREAK="============================================================"
echo -e Largest Files:$filesystem;
find $filesystem -mount -type f -ls|sort -rnk7 |head -20|awk '{printf "%d MB\t%s\n",($7/1024)/1024,$NF}';
echo -e "\n $BREAK"


BREAK="============================================================"
echo -e "...quick check to identify lsof in the system...";
function  check_os {
        if [[ $(cat /etc/os-release 2>&1 | grep '^ID' | awk '{print $1}' 2>&1 )  = *debian* ]]; then
        echo "... ...";
        elif [[ $(cat /etc/os-release 2>&1 | grep '^ID' | awk '{print $1}'  2>&1 )  != *debian* ]]; then
        echo "...";
        fi
}
check_os
ver=$(check_os)
function package_installed {
        if [[ $ver = "... ..." ]]; then
         if [ `dpkg -l | grep -i lsof | wc -l` -lt 1 ]; then
           apt-get install lsof  | grep -i 'Total download\|Installed:' -A1;
        fi
fi
}
package_installed
function package_installeda {
        if [[ $ver == "..." ]]; then
           if [[ `rpm -qa | grep -i lsof | wc -l` -lt 1 ]]; then
                yum  install lsof;
                fi
        fi
}
package_installeda;

BREAK="============================================================"
echo -e "\n Open Deleted Files:$filesystem";
lsof 2> /dev/null | grep $filesystem | grep deleted | wc -l
lsof 2> /dev/null | grep $filesystem | grep deleted| awk '{ if($7 > 1048576) print $7/1048576, "MB ",$9,$1 }' | sort -n -u | tail;
echo -e "\n $BREAK"
